version: '3.7'
services:

  iris:
    init: true
    build:
      context: .
    image: iris-demo:latest
    hostname: iris
    volumes: 
    - "./demo/:/tmp/iris"
    ports:
    - 52000:52773
    - 51000:1972
  postgres:
    image: postgres:13.4-alpine3.14
    hostname: postgres
    environment:
        POSTGRES_DB: demo
        POSTGRES_PASSWORD: demo
        POSTGRES_USER: demo
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "demo"]
        interval: 30s
        timeout: 30s
        retries: 3
    ports:
    - "5432:5432"
    volumes:
      - ./demo/postgreSQL:/docker-entrypoint-initdb.d/
#   mysql:
#     image: mysql:latest
#     hostname: mysql
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db'
#       # So you don't have to use root, but you can if you like
#       MYSQL_USER: 'user'
#       # You can use whatever password you like
#       MYSQL_PASSWORD: 'password'
#       # Password for root access
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       # <Port exposed> : < MySQL Port running inside container>
#       - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
#       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
#       # Names our volume
# volumes:
#     my-db:./volumes/mysql


