version: '3.7'
services:

  iris:
    init: true
    build:
      context: .
    image: iris-demo:latest
    hostname: iris
    volumes: 
    - "./demo/:/tmp/iris"
    ports:
    - 52000:52773
    - 51000:1972
  postgres:
    container_name: postgres
    image: postgres:13.4-alpine3.14
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 30s
        retries: 3
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    restart: unless-stopped
#   dbmysql:
#     image: mysql:latest
#     hostname: mysql
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db'
#       # So you don't have to use root, but you can if you like
#       MYSQL_USER: 'user'
#       # You can use whatever password you like
#       MYSQL_PASSWORD: 'password'
#       # Password for root access
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       # <Port exposed> : < MySQL Port running inside container>
#       - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
#       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
#       # Names our volume
# volumes:
#     my-db:./volumes/mysql
    # dboracle:
    #   image: oracle/database:12.1.0.2-ee
    #   volumes:
    #     - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    #   ports:
    #     - 1521:1521
    #     - 8080:8080
    #     - 5500:5500

