/// ZenTutorial.Application
Class ZenTutorial.Application Extends %ZEN.application
{

/// This is the name of this application.
Parameter APPLICATIONNAME = "ZenContacts";

/// This is the URL of the main starting page of this application.
Parameter HOMEPAGE = "ZenTutorial.HomePage.cls";

/// This Style block contains application-wide CSS style definitions.
XData Style
{
<style type="text/css">
</style>
}

}
